import { createContext } from 'react';
export const UserContext = createContext();
export const FeedbackPostsContext = createContext();
export const FeedbackItemListContext = createContext();
export const FeedbackItemContext = createContext();
export const AdminPostsContext = createContext();
export const AdminContext = createContext();
export const NavContext = createContext();
export const FooterContext = createContext();
export const LandingConext = createContext();
export const SignInContext = createContext();
export const TeamContext = createContext();
export const ErrorsContext = createContext();
export const UserPostsContext = createContext();
